branches:
  only:
  - cron
env:
  - CI=false
before_install:
  - git config --global user.name "Travis CI"
  - git config --global user.email "deploy@travis-ci.org"
  - git remote add icebase https://github.com/icebase/shadowsocks.git
  - git remote add shadowsocksrr https://github.com/shadowsocksrr/shadowsocksr.git
script:
  - git fetch icebase
  - git fetch shadowsocksrr
  - git push --force https://$REPO_TOKEN@github.com/cool2645/shadowsocksrr.git 'refs/remotes/icebase/*:refs/heads/icebase/*'
  - git push --force https://$REPO_TOKEN@github.com/cool2645/shadowsocksrr.git 'refs/remotes/shadowsocksrr/*:refs/heads/shadowsocksrr/*'
  - git merge icebase/manyuser -m "Merge branch 'icebase/manyuser' into ssrr-mu"
  - git merge shadowsocksrr/akkariiin/dev -m "Merge branch 'shadowsocksrr/akkariiin/dev' into ssrr-mu"
after_success:
  - git checkout -b ssrr-mu
  - git push --force https://$REPO_TOKEN@github.com/cool2645/shadowsocksrr.git ssrr-mu:ssrr-mu
